batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 94
model_path: Models/sentence_recognition\202306301742
train_epochs: 100
train_workers: 20
vocab: '3Erq1V;4#Phpdta.UyoBY9lG!

  :NkWCI7 wK"e,j8bcFXJ6nMz&fg20ZAT)L''iS(HmQ+5R-?/vsxOD*u'
width: 1408
